export enum TypeKind {
    Array = 'Array',
    Bool = 'Bool',
    Float = 'Float',
    Function = 'Function',
    FunctionGroup = 'FunctionGroup',
    Int = 'Int',
    Method = 'Method',
    MethodGroup = 'MethodGroup',
    Module = 'Module',
    Null = 'Null',
    String = 'String',
    Object = 'Object',
    TypeParameter = 'TypeParameter',
    Void = 'Void',
}
