export enum BoundNodeKind {
    ModuleDeclaration = 'ModuleDeclaration',
    InterfaceDeclaration = 'InterfaceDeclaration',
    InterfaceMethodDeclaration = 'InterfaceMethodDeclaration',
    ClassDeclaration = 'ClassDeclaration',
    ClassMethodDeclaration = 'ClassMethodDeclaration',
    FunctionDeclaration = 'FunctionDeclaration',
    DataDeclaration = 'DataDeclaration',

    DataDeclarationStatement = 'DataDeclarationStatement',
    IfStatement = 'IfStatement',
    ElseIfClause = 'ElseIfClause',
    ElseClause = 'ElseClause',
    SelectStatement = 'SelectStatement',
    CaseClause = 'CaseClause',
    DefaultClause = 'DefaultClause',
    ForLoop = 'ForLoop',
    WhileLoop = 'WhileLoop',
    RepeatLoop = 'RepeatLoop',
    ContinueStatement = 'ContinueStatement',
    ExitStatement = 'ExitStatement',
    TryStatement = 'TryStatement',
    CatchClause = 'CatchClause',
    ThrowStatement = 'ThrowStatement',
    ReturnStatement = 'ReturnStatement',
    ExpressionStatement = 'ExpressionStatement',

    AssignmentExpression = 'AssignmentExpression',
    GroupingExpression = 'GroupingExpression',
    ArrayLiteralExpression = 'ArrayLiteralExpression',
    IndexExpression = 'IndexExpression',
    SliceExpression = 'SliceExpression',
    SelfExpression = 'SelfExpression',
    SuperExpression = 'SuperExpression',
    NewExpression = 'NewExpression',
    InvokeExpression = 'InvokeExpression',
    BinaryExpression = 'BinaryExpression',
    UnaryExpression = 'UnaryExpression',
    IdentifierExpression = 'IdentifierExpression',
    NullExpression = 'NullExpression',
    BooleanLiteralExpression = 'BooleanLiteralExpression',
    IntegerLiteralExpression = 'IntegerLiteralExpression',
    FloatLiteralExpression = 'FloatLiteralExpression',
    StringLiteralExpression = 'StringLiteralExpression',
}
