export class Token {
    constructor(
        public kind: TokenKind,
        public start: number,
        public length: number) { }

    toJSON(): SerializableToken {
        return {
            kind: TokenKind[this.kind],
            start: this.start,
            length: this.length,
        };
    }
}

interface SerializableToken {
    kind: string;
    start: number;
    length: number;
}

export enum TokenKind {
    Unknown,
    EOF,
    Newline,
    Whitespace,
    Comment,
    StringLiteral,
    IntegerLiteral,
    FloatLiteral,
    
    IfDirectiveKeyword,
    ElseIfDirectiveKeyword,
    ElseDirectiveKeyword,
    EndDirectiveKeyword,
    RemDirectiveKeyword,
    RemDirectiveBody,
    PrintDirectiveKeyword,
    ErrorDirectiveKeyword,
    ConfigVar,
    
    Ampersand,
    OpeningParenthesis,
    ClosingParenthesis,
    Asterisk,
    PlusSign,
    Comma,
    HyphenMinus,
    Period,
    Slash,
    Colon,
    Semicolon,
    LessThanSign,
    EqualsSign,
    GreaterThanSign,
    QuestionMark,
    CommercialAt,
    OpeningSquareBracket,
    ClosingSquareBracket,
    VerticalBar,
    Tilde,
    
    Identifier,
    VoidKeyword,
    StrictKeyword,
    PublicKeyword,
    PrivateKeyword,
    ProtectedKeyword,
    FriendKeyword,
    PropertyKeyword,
    BoolKeyword,
    IntKeyword,
    FloatKeyword,
    StringKeyword,
    ArrayKeyword,
    ObjectKeyword,
    ModKeyword,
    ContinueKeyword,
    ExitKeyword,
    IncludeKeyword,
    ImportKeyword,
    ModuleKeyword,
    ExternKeyword,
    NewKeyword,
    SelfKeyword,
    SuperKeyword,
    EachInKeyword,
    TrueKeyword,
    FalseKeyword,
    NullKeyword,
    NotKeyword,
    ExtendsKeyword,
    AbstractKeyword,
    FinalKeyword,
    SelectKeyword,
    CaseKeyword,
    DefaultKeyword,
    ConstKeyword,
    LocalKeyword,
    GlobalKeyword,
    FieldKeyword,
    MethodKeyword,
    FunctionKeyword,
    ClassKeyword,
    AndKeyword,
    OrKeyword,
    ShlKeyword,
    ShrKeyword,
    EndKeyword,
    IfKeyword,
    ThenKeyword,
    ElseKeyword,
    ElseIfKeyword,
    EndIfKeyword,
    WhileKeyword,
    WendKeyword,
    RepeatKeyword,
    UntilKeyword,
    ForeverKeyword,
    ForKeyword,
    ToKeyword,
    StepKeyword,
    NextKeyword,
    ReturnKeyword,
    InterfaceKeyword,
    ImplementsKeyword,
    InlineKeyword,
    AliasKeyword,
    TryKeyword,
    CatchKeyword,
    ThrowKeyword,
    ThrowableKeyword,
    
    Expression,
}